name: Simple Test Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk
        
    - name: Test basic setup
      run: |
        python --version
        pip --version
        ls -la
        
    - name: Test tkinter
      run: |
        python -c "import tkinter; print('tkinter works')"
        
    - name: Check keyreplacer module
      run: |
        ls -la keyreplacer/
        python -c "import sys; sys.path.insert(0, '.'); import keyreplacer; print('Import successful')"
        
    - name: Install minimal dependencies
      run: |
        pip install keyboard pyautogui pillow appdirs pyinstaller
        
    - name: Test PyInstaller
      run: |
        python -m PyInstaller --version
        
    - name: Test simple build
      run: |
        python -m PyInstaller keyreplacer/main.py --name=test-build --onefile --windowed --hidden-import=keyreplacer
        ls -la dist/
